client/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
import views


urlpatterns = [

	        url(r'^client-page/$', views.client_page,  name="client_page"),
	        url(r'^booking/category/(?P<status>.+)/$', views.booking_category, name='booking_category'),
	        url(r'^client/search/$', views.search, name='search'),
	        url(r'^client/get-booking/$', views.get_booking, name='get_booking'),
	        url(r'^search-home/$', views.search_home, name='search_home'),

			
	]

diasporaSuites/urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.shortcuts import render, render_to_response

from django.template import RequestContext
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap

# from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

from general.views import homepage



def server_error(request):
    response = render(request, "500.html")
    response.status_code = 500
    return response

#page not found
def custom_404(request):
    response = render(request, "404.html")
    response.status_co


urlpatterns = [

    url(r'^$', homepage, name='homepage'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^general/', include("general.urls", namespace="general")),
    url(r'^client/', include("client.urls", namespace="client")),
	url(r'^backend/', include("backend.urls", namespace="backend")),
    

    #change password urls
    # url(r'^reset/form/$', TemplateView.as_view(template_name = 'registration/password_reset_email.html')),
    # url(r'^resetpassword/passwordsent/$', password_reset_done, name="password_reset_done"),
    # url(r'^resetpassword/$', password_reset, name="password_reset"),
    # url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name="password_reset_confirm"),
    # url(r'^reset/done/$', password_reset_complete, name="password_reset_complete"),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

general/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
import views


urlpatterns = [

	        url(r'^$', views.homepage,  name="homepage"),
	        url(r'^signup/Page/$', views.userregister,  name="userregister"),
			url(r'^login/Page/$', views.userlogin,  name="login"),
            url(r'^logout/$', views.user_logout, name='user_logout'),
            url(r'^bookings/(?P<room_id>[-\w]+)/$', views.booking, name='make_booking'),
            url(r'^action/(?P<status>.+)/(?P<booking_id>[-\w]+)/$', views.action_taken, name='action_taken'),
            url(r'^create_booking/$', views.create_booking, name='create_booking'),
            url(r'^successful_registration/$', views.successful_registration, name='successful_registration'),
            
			
	]

general/forms.py
from django import forms
from general.models import UserAccount
from django.forms import ModelForm, Textarea
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
# from general.modelchoices import STATES, COUNTRY, TITLE
#from captcha.fields import CaptchaField
# from nocaptcha_recaptcha.fields import NoReCaptchaField
# from general.modelfield_choices import HOW_DID_YOU_FIND_US, INDUSTRY, PAYMENT

attrs3 = {'class': 'form-control','required': 'true'}



class LoginForm(forms.ModelForm):
    email      =    forms.EmailField(max_length = 128, help_text = "",widget=forms.TextInput(attrs={'placeholder': 'Email','class': 'form-group form-control'}))
    password   =    forms.CharField(max_length=15, widget=forms.PasswordInput(attrs={'placeholder':'Password','class': 'form-group form-control'}))

    class Meta:
       # Associate form with a model
       	model = User
        fields = ('email','password',)



class UserForm(forms.ModelForm):
	first_name      =    forms.CharField(max_length = 128, help_text = "",widget=forms.TextInput(attrs={'class': 'form-group form-control','required': 'true'}))
	username        =    forms.CharField(max_length = 128, help_text = "",widget=forms.TextInput(attrs={'class': 'form-group form-control','required': 'true'}))
	email           =    forms.EmailField(max_length = 128, help_text = "",widget=forms.EmailInput(attrs={'class': 'form-group form-control','required': 'true'}))
	password        =    forms.CharField(max_length=15, widget=forms.PasswordInput(attrs={'placeholder':'Password','class': 'form-group form-control','required': 'true'}))
	
	class Meta:
		model = User
		fields =  ('username','email','password','first_name',)



class UserAccountForm(forms.ModelForm):
    password2       = forms.CharField(max_length=15, widget=forms.PasswordInput(attrs={'placeholder':'Password','class': 'form-group form-control','required': 'true'}))
    phone_number    = forms.CharField(max_length = 150, help_text="", widget=forms.TextInput(attrs=attrs3))
 
    
    class Meta:
        model = UserAccount
        fields = ('phone_number','password2',)

general/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import render_to_response, render, redirect, get_object_or_404
from django.core.serializers.json import DjangoJSONEncoder
from django.http import Http404, HttpResponse , HttpResponseRedirect, JsonResponse
from django.forms.models import model_to_dict
from django.contrib.auth.decorators import user_passes_test
from general.models import *
from client.models import *
from general.forms import UserForm, UserAccountForm, LoginForm
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.contrib.auth.models import User
from itertools import chain
from operator import attrgetter
from django.core import serializers
from django.db.models import Q
from django.contrib import messages
from django.template.context import RequestContext
from django.db.models import Count
from django import template
from itertools import chain
import re
import hashlib
import random, datetime
import urllib
import time
from django.core.urlresolvers import reverse
from django.utils.timezone import utc
import json,random,string
from django.db.models import Sum
from django.template.loader import get_template
from django.template import Context
from django.core.mail import EmailMessage, send_mail
# from matchingApp.models import MessageCenterComment
# from lvtvAdmin.views import paginate_list
# from lvtvguinea.settings import EMAIL_HOST_USER
# Create your views here.


def homepage(request):
	context = {}
	room_types = RoomType.objects.all()
	context['rooms'] = room_types
	template_name = 'general/homepage.html'
	return render(request, template_name, context)


def userlogin(request):
	context = {}
	username  = ""
	context['login_form'] = LoginForm()

	if request.method == "POST":
	    form = LoginForm(data = request.POST)

	    if form.is_valid:
	        email    = request.POST.get('email').strip()
	        password = request.POST.get('password').strip()
	        
	        user_account =  User.objects.filter((Q(email= email) | Q(useraccount__phone_number=email)))
	        
	        if not user_account.exists():
				context['email_not_found'] = True
				context['email'] = email
				return render(request, 'general/login.html', context )

	        if user_account.exists():
	            username = user_account[0].username
	        auth_user = authenticate(username = username, password = password)

	        if auth_user is not None:
	            user = auth_user

	            if user.is_active:
	                login(request, user)                    

	                if user.is_staff:
	                    response =  redirect(reverse('backend:admin_home'))
	                    return response
	                   
	                else:
	                    response = redirect(reverse("client:client_page"))
	                    return response
	        else:
	            # print "No details found for %s" %(email)
	            context['no_record_found'] = True
	        return render(request, 'general/login.html', context )
	else:
		return render(request, 'general/login.html',context)
	# context = {}
	# template_name = 'general/login.html'
	# return render(request, template_name, context)


def userregister(request):
	print "Got here"
	context = {}	
	
	user_form = UserForm()
	user_account_form = UserAccountForm()
	
	context['user_form'] = user_form
	context['user_account_form'] = user_account_form
	
	if  request.method            ==     "POST":
		rp                         =     request.POST
		print "rp:",rp	        
		userform                   =     UserForm(request.POST)
		user_account_form          =     UserAccountForm(request.POST)
		print "here1"
		if User.objects.filter(username = rp.get('username')).exists():                
			return render(request, 'general/register.html', {'user_form':userform, 'user_account_form':user_account_form,'username_is_taken':True})
		if User.objects.filter(email = rp.get('email')).exists():                
			return render(request, 'general/register.html', {'user_form':userform, 'user_account_form':user_account_form,'email_is_taken':True})
		if UserAccount.objects.filter(phone_number = rp.get('phone_number')).exists():
			return render(request, 'general/register.html', {'user_form':userform, 'user_account_form':user_account_form,'phone_is_taken':True})
		else:
			print "here2"
			if userform.is_valid and user_account_form.is_valid:
				print "here3"
				password1     = rp.get('password')
				password2     = rp.get('confirm_password')
				if password1 != password2:
					return render(request, 'general/register.html', {'user_form':userform, 'user_account_form':user_account_form,'password_mismatch':True})
				if len(password1) < 6:
					return render(request, 'general/register.html', {'user_form':userform, 'user_account_form':user_account_form,'password_too_short':True})
				user = User.objects.create(username = rp.get('username'), email = rp.get('email').lower(),
					first_name = rp.get('first_name'), last_name = rp.get('first_name'))
				user.set_password(rp.get('password')) 
				user.save()
				print 'here4'
				new_user_account = UserAccount.objects.create(
					user = user,
					phone_number = rp.get('phone_number'),
					created_on   = datetime.datetime.now())
				print 'here5'
				context['user_is_created']  =    True
				context['email']            =    rp.get('email')
				print "user creation for %s successful" %(user)
				return redirect(reverse('general:successful_registration'))
			else:
				print "errors detected"                    
				return render(request, 'general/register.html', context)  
	
		return redirect(request.META['HTTP_REFERER'])
	else:
		return render(request, 'general/register.html',context)


def user_logout(request):
	response = redirect(reverse('general:homepage'))
	logout(request)
	return response


def create_booking_number(value):
	allowed_chars = ''.join((string.uppercase, string.digits))
	unique_id = ''.join(random.choice(allowed_chars) for _ in range(9))
	return value + unique_id


def successful_registration(request):
    context = {}    
    return render(request, 'general/successful.html', context)



def booking(request,room_id):
	context = {}
	if request.user.is_staff:
		return redirect(reverse('backend:admin_home'))
	else:
		room_type = RoomType.objects.get(id=room_id)
		context['room_numbers'] = room_type.roomnumber_set.all()
		context['room_type'] = room_type
		return render(request,'general/bookRoom.html', context)



def create_booking(request):
	if request.method == "POST":
		context = {}
		rp = request.POST
		print rp

		from_date = (datetime.datetime.strptime(str(rp.get('from')), '%m/%d/%Y'))

		try:
			end_date = (datetime.datetime.strptime(str(rp.get('to')), '%m/%d/%Y'))
		except:
			end_date = rp.get('to')

		print from_date, end_date
		print type(from_date)

		current_time = datetime.datetime.now()
		print current_time

		if str(end_date) == "" and (str(from_date) > str(current_time)):
			days = 1

		elif str(end_date) == "" and (str(from_date) < str(current_time)):
			days = 0
			messages.warning(request,'Check in date is less than current time and date!!!')
			return redirect(request.META.get('HTTP_REFERER'))

		elif rp.get('from') == rp.get('to'):
			days = 0
			messages.warning(request,'check in date cannot be same as check out date!!!')
			return redirect(request.META.get('HTTP_REFERER'))

		elif rp.get('to') < rp.get('from'):
			days = 0
			messages.warning(request,'check in date cannot be greater than check out date!!!')
			return redirect(request.META.get('HTTP_REFERER'))

		elif (str(from_date) or str(end_date)) < str(current_time):
			days = 0
			messages.warning(request,'Oops it seems the check in date or check out dates is less than current time and date!!!')
			return redirect(request.META.get('HTTP_REFERER'))


		room_type = RoomType.objects.get(id=rp.get('room_type_id')).room_type
		room_number = RoomNumber.objects.get(id=rp.get('room_number')).room_number

		# from_dt = datetime.datetime.strptime(str(rp.get('from')), '%m-%d-%Y %H:%M:%S').strftime('%A')

		try:
			active_bookings = Bookings.objects.filter(room_id=rp.get('room_type_id'), new_booking=True)
		except Exception as e:
			pass 


		for booking in active_bookings:

			book_in_date = datetime.datetime.strptime(str(booking.checK_in), '%Y-%m-%d %H:%M:%S')
			
			book_out_date = datetime.datetime.strptime(str(booking.checK_out), '%Y-%m-%d %H:%M:%S')
			
			try:
				if booking.room_number == room_number:
					if (book_in_date <= from_date <= book_out_date):
						messages.warning(request,'Room already booked for check in date please select another room or date')
						return redirect(request.META.get('HTTP_REFERER'))
					else:
						pass
			except Exception as e:
				pass

		amount = float(rp.get('room_cost')) * float(rp.get('nod'))

		try:

			create_booking = Bookings.objects.create(
				user=request.user,
				tracking_number=create_booking_number('DPS-BKN'),
				ref_num=rp.get('pay_ref'),
				checK_in = from_date,
				checK_out = end_date,
				room_type = room_type,
				room_id = rp.get('room_type_id'),
				room_number = room_number,
				days=rp.get('nod'),
				amount_paid=amount)

			messages.success(request,'Well done! You successfully created a booking!!!')
			return redirect(reverse('client:client_page'))

		except:

			create_booking = Bookings.objects.create(
				tracking_number=create_booking_number('DPS-BKN'),
				ref_num=rp.get('pay_ref'),
				checK_in = from_date,
				checK_out = end_date,
				room_type = room_type,
				room_id = rp.get('room_type_id'),
				room_number = room_number,
				days=rp.get('nod'),
				amount_paid=amount)

			template_name = 'client/anonymous_booking.html'
			context['reservation'] = create_booking
			return render(request,template_name,context)

	return render(request.META['HTTP_REFERER'])


@login_required

general/templates/general/login.html
{% extends 'general/bookRoom.html' %}
{% load staticfiles %}


{% block contents %}
 
<section id="about" >
    <div class="container">
        <div class="row"> 
            <div class="col-md-12">
                <div class="about-logo">
                    <p>Please sign in here</p>
                    <p>Dont have an account with us? Please sign up <a href="{% url 'general:userregister' %}"> HERE </a> to enjoy many benefits we have to offer to our registered clients</p>
                    <p></p>
                    <p>NB: Fields with<b style="color:red">'*'</b> are required</p>

                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-6">
                           <!-- Form itself -->
        <form action="{% url 'general:login' %}" method="POST">
          {% csrf_token %}
           <h3>Sign in form</h3>

           {% if not email_not_found %}
            <div class="control-group">
                <div class="controls">
                <p class="">e-mail/Phone Number</p>
                <input type="text" class="form-control" 
                        id="email" name="email" required
                           data-validation-required-message="Please enter your phone number or email" />
               </div>
             </div><br/>
            {% else %}         
             <div class="control-group">
                <div class="controls">
                <p class="">e-mail/Phone Number</p>
                <input type="text" class="form-control" 
                        id="email" name="email" required value="{{email}}"
                           data-validation-required-message="Please enter your phone number or email" />
                  {% if email_not_found %}         
                    <p class="help-block" style="color:red;">Email/Phone number does not exist</p>
                  {% endif %}
               </div>
             </div> <br/>
             {% endif %}

              <div class="control-group">
                  <div class="controls">
                    <p class="">Password</p>
                    <input type="password" class="form-control" 
                            id="password" name="password" required
                       data-validation-required-message="Please enter your password" />
                        {% if no_record_found %}
                            <p class="help-block" style="color:red;">Oops something is wrong with either the email/phone number and password combination entered</p>
                        {% endif %}
                </div>
            </div><br/>      

            <div id="success"> </div> <!-- For success/fail messages -->
            <button type="submit" class="btn btn-primary pull-right">Submit</button><br />
        </form>
<!--           <a href="/resetpassword/">Forgot password</a>
 -->
            </div>
            <div class="col-md-6">
            </div>
        </div>
    </div>
</section><!--/#about-->
<section id="hero-action-section" class="hero-action-section">
    <!-- .Container -->
    <div class="container ow-section">
        <h3 class="hero-action-subtitle">Our services are top class</h3>
        <h4 class="hero-action-title">Guaranteed to get value for your money</h4>
        <p class="hero-action-description">So what are you waiting for....
        </p>
        <p><a href="#/pricing" class="get-started" style="width:250px;">Make a reservation Now!!!</a></p>
    </div><!-- /.Container -->
</section>

{% endblock contents %}

general/templates/general/register.html
{% extends 'general/bookRoom.html' %}
{% load staticfiles %}


{% block contents %}
 
<section id="about">
    <div class="container">
            <div class="row"> 
                <div class="col-md-12">
                    <div class="about-logo">
                        <p>Hi,</p>
                        <p>Please sign up here and enjoy the many benefits of being our guest<b style="color:red;"></b></p>
                        <p>NB: Fields with<b style="color:red">'*'</b> are required</p>
                        <p>Already signed up please click <a href="{% url 'general:login' %}"> HERE </a>to login in</p>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-md-6">                         
                    <!-- Form itself -->
                    <form action="{% url 'general:userregister' %}" method="POST">
                    {% csrf_token %}

                   <h3>Sign Up form</h3>

                    <div class="control-group">
                        <div class="controls">
                        <p class="">First name</p>
                            {{user_form.first_name}}
                          <p class="help-block"></p>
                       </div>
                     </div>
                    

                     <div class="control-group">
                        {% if not username_is_taken %}
                         <div class="controls">
                            <p class="">Username</p>
                            {{user_form.username}}
                            <p class="help-block"></p>
                        </div>
                        {% else %}
                         <div class="controls">
                            <p class="">Username</p>
                            {{user_form.username}}
                             <p class="help-block" style="color:red">Username already exist</p>
                          </div>
                        {% endif %}
                     </div> 

                     <div class="control-group">
                        {% if not email_is_taken %}
                          <div class="controls">
                            <p class="">E-mail</p>
                            {{user_form.email}}
                          </div>
                        {% else %}
                        <div class="controls">
                            <p class="">E-mail</p>
                            {{user_form.email}}
                            <p class="help-block" style="color:red">E-mail already taken</p>
                        </div>
                        {% endif %}
                    </div> 

                    <div class="control-group">
                        {% if not phone_is_taken %}
                        <div class="controls">
                            <p class="">Phone Number</p>
                            {{user_account_form.phone_number}}         
                            <p class="help-block"></p>
                        </div>
                        {% else %}
                          <div class="controls">
                            <p class="">Phone Number</p>
                            {{user_account_form.phone_number}}
                            <p class="help-block" style="color:red">Phone Number already exists</p>
                         </div>
                        {% endif %}

                    </div>

                    {% if password_mismatch %} 

                        <div class="control-group">
                              <div class="controls">
                                <p class="">Password</p>
                                <input type="password" class="form-control" 
                                        id="password" name="password" required
                                   data-validation-required-message="Please enter your password" />
                                <p class="help-block"></p>
                            </div>
                        </div> 

                        <div class="control-group">
                              <div class="controls">
                                <p class="">Confirm password</p>
                                <input type="password" class="form-control"
                                        id="confirm_password" name="confirm_password" required
                                   data-validation-required-message="Please confirm your password" />
                                <p class="help-block" style="color:red">Sorry passwords do not match</p>

                            </div>
                        </div>

                    {% elif password_too_short %}

                        <div class="control-group">
                              <div class="controls">
                                <p class="">Passowrd</p>
                                <input type="password" class="form-control" 
                                        id="password" name="password" required
                                   data-validation-required-message="Please enter your password" />
                                <p class="help-block"></p>
                            </div>
                        </div> 

                        <div class="control-group">
                              <div class="controls">
                                <p class="">Confirm password</p>
                                <input type="password" class="form-control"
                                        id="confirm_password" name="confirm_password" required
                                   data-validation-required-message="Please confirm your password" />
                                <p class="help-block" style="color:red">Password to short(Passwords should be at least six characters long)</p>

                            </div>
                        </div>

                    {% else %}

                        <div class="control-group">
                              <div class="controls">
                                <p class="">Password</p>
                                <input type="password" class="form-control" 
                                        id="password" name="password" required
                                   data-validation-required-message="Please enter your password" />
                                <p class="help-block"></p>
                            </div>
                        </div> 

                        <div class="control-group">
                              <div class="controls">
                                <p class="">Confirm password</p>
                                <input type="password" class="form-control"
                                        id="confirm_password" name="confirm_password" required
                                   data-validation-required-message="Please confirm your password" />
                                <p class="help-block"></p>

                            </div>
                        </div>

                    {% endif %}
 
                    <div id="success"> </div> <!-- For success/fail messages -->
                    <button type="submit" class="btn btn-primary pull-right">Submit</button><br />
                    </form>
                    <!-- endform -->
                </div>
                <div class="col-md-6">
                </div>
            </div>
        </div>
</section>
<section id="hero-action-section" class="hero-action-section">
    <!-- .Container -->
    <div class="container ow-section">
        <h3 class="hero-action-subtitle">Our services are top class</h3>
        <h4 class="hero-action-title">Guaranteed to get value for your money</h4>
        <p class="hero-action-description">So what are you waiting for....
        </p>
        <p><a href="#/pricing" class="get-started" style="width:250px;">Make a reservation Now!!!</a></p>
    </div><!-- /.Container -->
</section>

{% endblock contents %}

general/templates/general/search.html
{% extends 'general/bookRoom.html' %}
{% load staticfiles %}


{% block contents %}
 
<section id="about" >
    <div class="container">
        <div class="row"> 
            <div class="col-md-12">
                <div class="about-logo">


                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-6">
            	{% if message %}
            		<p>Not found</p>
            	{% else %}
	               	<p>Booking Number: {{reservation.tracking_number}}</p>
			        <p>Room Type: {{reservation.room_type}}</p>
			        <p>Room Number: {{reservation.room_number}}</p>
			        <p>Check in Date: {{reservation.checK_in}}</p>
			        <p>Check out Date: {{reservation.checK_out}}</p>
			        <p>Number of Days: {{reservation.days}}</p>
			        <p>Amount: ₦{{reservation.amount_paid}}</p>
			        <p>Payment Reference Number: {{reservation.ref_num}}</p>
			        <p>Status: {{reservation.status}}</p> 
			    {% endif %}           <!-- Form itself -->
            </div>
            <div class="col-md-6">
            </div>
        </div>
    </div>
</section><!--/#about-->
<section id="hero-action-section" class="hero-action-section">
    <!-- .Container -->
    <div class="container ow-section">
        <h3 class="hero-action-subtitle">Our services are top class</h3>
        <h4 class="hero-action-title">Guaranteed to get value for your money</h4>
        <p class="hero-action-description">So what are you waiting for....
        </p>
        <p><a href="#/pricing" class="get-started" style="width:250px;">Make a reservation Now!!!</a></p>
    </div><!-- /.Container -->
</section>

{% endblock contents %}

general/templates/general/successful.html
{% extends 'general/bookRoom.html' %}
{% load staticfiles %}


{% block contents %}
 
<section id="about" style="position: relative;top: 50px;" >
    <div class="container">
        <div class="row"> 
            <div class="col-md-12">
                <div class="about-logo">
                    <div class="about-text">
                      <h1>Welcome!!!</h1><br>
                      <p style="position: relative; bottom: 30px;">Your registration was successful. Please follow this <a href="{% url 'general:login' %}"> LINK </a> and login to start making your reservations</p>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section><!--/#about-->
<section id="hero-action-section" class="hero-action-section">
    <!-- .Container -->
    <div class="container ow-section">
        <h3 class="hero-action-subtitle">Our services are top class</h3>
        <h4 class="hero-action-title">Guaranteed to get value for your money</h4>
        <p class="hero-action-description">So what are you waiting for....
        </p>
        <p><a href="#/pricing" class="get-started" style="width:250px;">Make a reservation Now!!!</a></p>
    </div><!-- /.Container -->
</section>

{% endblock contents %}